### ISSUE TITLE
Octolinker incorrectly identifies modules in Rust even when they are not specified

### ISSUE THREAD

**Issue by cynicaldevil** [OctoLinker/browser-extension#371]
**Browser name:** 
Chrome

**Browser version:** 
Version 59.0.3071.115 (Official Build) (64-bit)

**OctoLinker version:** 
4.12.0

**URL and line number where issue occurs:** 
https://github.com/cynicaldevil/rust/commit/9713020dbe338e2a576b656d17f0415df26862a8#commitcomment-23137541

In this GH comment, Octolinker incorrectly assumes any word that comes after `use` as a module/package name.

**Comment by josephfrazier** [comment]
This is similar to https://github.com/OctoLinker/browser-extension/issues/284

**Comment by cynicaldevil** [comment]
I didn't go over the source thoroughly, but I think that the regex [here](https://github.com/OctoLinker/browser-extension/blob/8b25456aa6921a5a575114c3220ed11d517315e6/packages/helper-grammar-regex-collection/index.js#L80) needs to be changed to be more exclusive.

**Comment by josephfrazier** [comment]
Yeah, we should probably change that `\b` to a `^`. Want to send a PR?

**Comment by cynicaldevil** [comment]
Sure! I think I'll send one tomorrow.

**Comment by cynicaldevil** [comment]
Running the command `yarn test` is giving me this error message:
```
/home/nikhil/workspace/browser-extension/node_modules/eslint-config-airbnb-base/rules/variables.js:
	Configuration for rule "no-use-before-define" is invalid:
	Value "[object Object]" no (or more than one) schemas match.

Referenced from: airbnb-base
Referenced from: /home/nikhil/workspace/browser-extension/.eslintrc
Error: /home/nikhil/workspace/browser-extension/node_modules/eslint-config-airbnb-base/rules/variables.js:
	Configuration for rule "no-use-before-define" is invalid:
	Value "[object Object]" no (or more than one) schemas match.

Referenced from: airbnb-base
Referenced from: /home/nikhil/workspace/browser-extension/.eslintrc
    at validateRuleOptions (/home/nikhil/workspace/browser-extension/node_modules/addons-linter/node_modules/eslint/lib/config/config-validator.js:109:15)
    at Object.keys.forEach.id (/home/nikhil/workspace/browser-extension/node_modules/addons-linter/node_modules/eslint/lib/config/config-validator.js:156:13)
    at Array.forEach (native)
    at Object.validate (/home/nikhil/workspace/browser-extension/node_modules/addons-linter/node_modules/eslint/lib/config/config-validator.js:155:35)
    at load (/home/nikhil/workspace/browser-extension/node_modules/addons-linter/node_modules/eslint/lib/config/config-file.js:522:19)
    at configExtends.reduceRight (/home/nikhil/workspace/browser-extension/node_modules/addons-linter/node_modules/eslint/lib/config/config-file.js:391:36)
    at Array.reduceRight (native)
    at applyExtends (/home/nikhil/workspace/browser-extension/node_modules/addons-linter/node_modules/eslint/lib/config/config-file.js:362:28)
    at load (/home/nikhil/workspace/browser-extension/node_modules/addons-linter/node_modules/eslint/lib/config/config-file.js:529:22)
    at configExtends.reduceRight (/home/nikhil/workspace/browser-extension/node_modules/addons-linter/node_modules/eslint/lib/config/config-file.js:391:36)
```
I'm getting this without any changes too. Is this a known issue?

**Comment by josephfrazier** [comment]
Hmm, I'm seeing that locally as well. However, the Travis builds are still working (here's a [https://travis-ci.org/OctoLinker/browser-extension/builds/255847673](https://travis-ci.org/OctoLinker/browser-extension)). Not sure what's going on...

**Comment by stefanbuck** [comment]
I don't have this issue and `yarn test` pass successfully!? 

```
yarn v0.20.3
node v8.1.2
```

**Comment by josephfrazier** [comment]
It seems to have something to do with the version of yarn. Upgrading from `v0.27.5` to `v0.28.4` and reinstalling `./node_modules` fixed it for me.

```bash
yarn v0.28.4
node v8.2.0
```

**Comment by cynicaldevil** [comment]
I am having trouble updating yarn due to some restrictions in my college network, so it might be some time before I am able to make a PR.

**Comment by josephfrazier** [comment]
Oh, feel free to make a PR without running the tests locally. It's a fairly straightforward change, so I'd expect the tests to continue passing on Travis. If they don't, I'd be happy to help fix them.
